### PR TITLE
Enable multiple menus, introducing new UI

### PR DESCRIPTION
**Pull request by pnicolli**
This is a big one :)

This PR introduces a whole new logic, and it drops Plone 4 compatibility.
The configuration is now saved in a json string. The json object can hold multiple configurations. We can now have a different menu configuration for different subsections of the plone site. This is useful for example with subsites.

The controlpanel for the menu has been rebuilt from scratch with a React-based widget.

### CODE REVIEW

**Comment by cekk** [comment]
if you improve also the README with infos about how to use the control panel and some screenshots (or an animated gif), we can release it on pypi ;)

**Comment by pnicolli** [comment]
Done. Also fixed a couple minor bugs along the way :)
What do you think of the new readme?

**Comment by luca-bellenghi** [comment]
Think it's ok. Could be nice to have some test before release it on pypi,
but right now could be enough to clarify that test are missing.

I also think you could release a major. This product seems to be ready to be a 1.0. Is it?

**Comment by nzambello** [comment]
Having issues with this. In a new and clean site, I was installing a theme which has this add-on as a depencency (it was in development with this branch active) and said me that `Cannot find a record with name 'collective.editablemenu.browser.interfaces.IEditableMenuSettings.menu_tabs_json'`.

Furthermore, in a existing site, I switched to this branch and it brokes when I try to open submenus:
```AttributeError: 'function' object has no attribute 'listFolderContents'

 - Expression: "view/get_menu_subitems"
 - Filename:   ... ve/editablemenu/browser/templates/submenu_detail_view.pt
 - Location:   (line 8: col 27)
 - Source:     ... tal:define="subitems view/get_menu_subitems;```

**Comment by nzambello** [comment]
Fixed with @pnicolli

**Comment by nzambello** [comment]
@cekk @pnicolli I'm not ok with the split on "\n" in menu title items here: https://github.com/RedTurtle/collective.editablemenu/blob/15b3aaff309a2896dcba6761f514184223902ad5/src/collective/editablemenu/browser/menu_support_view.py#L103

If I split only on "\n" it works well and I have two separated <span>, but as it is, with the split on "\r\n" the pattern is not matched (I havo no "\r").

What should I do? Can I remove the "\r" or it is better to do two separated splits or something else?

**Pull request merged**
